export const menuFilters = [
  {
    title: "gender",
    filters: [
      {
        title: "Sertanejo",
        subFilters: [
          "Todos",
          "Pop",
          "Romântico",
          "Bachata",
          "Raíz- viola/ modão",
          "Arrocha",
          "Vaneira",
          "Forró- pisadinha - universitário - forronejo",
          "Country",
          "Funknejo",
          "Brega",
          "Sofrencia",
          "Reggeaton",
        ],
      },
      {
        title: "Rock",
        subFilters: [
          "Todos",
          "Pop rock",
          "Rock alternativo",
          "Grunge",
          "Punk rock",
          "Pop punk",
          "New wave",
          "Heavy metal",
          "Hardcore",
          "Hard rock",
          "Folk rock",
          "Glam rock",
          "Rock progressivo",
          "Rock psicodélico",
          "Surf Music",
          "Indie Rock",
          "Emo",
          "Metalcore",
          "Post-Hardcore",
          "Post-Punk",
        ],
      },
      {
        title: "Samba",
        subFilters: [
          "Todos",
          "Samba de breque",
          "Samba de partido alto",
          "Samba raiz",
          "Samba choro",
          "Samba sincopado",
          "Samba carnavalesco",
          "Sambalanço",
          "Samba rock",
          "Samba reggae",
          "Bossa nova",
          "MPB",
        ],
      },
      {
        title: "Gospel",
        subFilters: [
          "Todos",
          "Hinos",
          "Louvores",
          "Forró gospel",
          "Rock gospel",
          "Axé gospel",
          "Worship",
          "Funk gospel",
        ],
      },
      {
        title: "Funk",
        subFilters: ["Todos", "Ostentação", "Carioca", "Consciente", "Pop"],
      },
      {
        title: "Infantil",
        subFilters: ["Todos", "Cantigas de roda", "Poéticas"],
      },
      {
        title: "Pagode",
        subFilters: ["Todos", "Pagode carioca", "Pagode baiano", "Axé"],
      },
      {
        title: "Jazz",
        subFilters: ["Todos", "Blues", "Soul", "RnB", "Zouk", "Ska"],
      },
      {
        title: "Latina",
        subFilters: [
          "Todos",
          "Reggeaton",
          "Tango",
          "Cumbia",
          "Conga",
          "Merengue",
          "Salsa",
          "Lambada",
        ],
      },
      {
        title: "Reggae",
        subFilters: [
          "Todos",
          "Early reggae",
          "Roots reggae",
          "Rockers",
          "Dancehall",
          "New roots",
          "Rock reggae",
          "Pop reggae",
          "Samba reggae",
        ],
      },
      {
        title: "Eletrônica",
        subFilters: [
          "Todos",
          "House",
          "Acid house",
          "Drum and bass",
          "Psy and Trance",
          "Electro music",
          "Lounge",
          "Minimal",
          "Techno",
          "Tech house",
          "Braziliam Bass",
          "Dance Music",
          "Euro Dance",
          "Deep House",
          "Música psicadélica",
          "Noise",
          "New wave (música)",
          "New age",
          "Hip hop",
          "Dub",
          "Música ambiente",
        ],
      },
      {
        title: "HIP HOP",
        subFilters: ["Todos", "Rap", "DJing", "Break dance", "Graffiti"],
      },
      {
        title: "Pop Internacional",
        subFilters: [
          "Todos",
          "K-pop",
          "Dance",
          "Sunshine",
          "Experimental",
          "Progressivo",
          "Tean",
          "Operation",
          "Art",
          "Bubblegun",
          "Hypnagogic",
          "Indie Pop",
          "Hyperpop",
          "Synth Pop",
          "Pop",
        ],
      },
      {
        title: "Pop",
        subFilters: ["Pop"],
      },
      {
        title: "Outros",
        subFilters: ["Fonograma"],
      },
    ],
  },
  {
    title: "mood",
    filters: [
      {
        title: "Moods",
        subFilters: [
          "Feliz",
          "Triste",
          "Romântico",
          "Sombrio",
          "Melancólico",
          "Dramático",
          "Groove",
          "Tenso",
          "Animado",
          "Esperançoso",
          "Inspirador",
          "Vibrante",
          "Calmo",
          "Agitado",
        ],
      },
    ],
  },
  {
    title: "license",
    filters: [
      {
        title: "Liberação",
        subFilters: [],
      },
      {
        title: "Liberação Exclusiva",
        subFilters: [],
      },
      {
        title: "Venda Completa",
        subFilters: [],
      },
      {
        title: "Venda Parcial",
        subFilters: [],
      },
      // {
      //   title: 'Leilão',
      //   subFilters: []
      // }
    ],
  },
  {
    title: "price",
    filters: [],
  },
];
